/*
Originalmente, la tabla transporte fue creada y llenada de la siguiente manera:
*/

CREATE TABLE TRANSPORTE (
    "id" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(60) NOT NULL,
    direccion VARCHAR(60) NOT NULL,
	comuna VARCHAR(60) NOT NULL,
);

INSERT INTO TRANSPORTE (nombre, direccion, comuna)
SELECT nombre, direccion, comuna
FROM TRANSPORTES_ORIGINAL;

/*
Luego, tras una modificación que hice al modelo relacional, se deben hacer las modificaciones para que quede como si hubiera sido creada de la siguiente forma:
*/

CREATE TABLE TRANSPORTE (
    "id" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(60) NOT NULL,
    id_direccion NUMBER NOT NULL,
    FOREIGN KEY (id_direccion) REFERENCES DIRECCION("id")
);

/*
Para lograrlo, considerando que ya existía esta tabla, se ejecutaron las siguientes operaciones:

1. Se reparan de forma manual en Oracle SQL Developer los caracteres erróneos dentro de los campos de texto (vocales con tílde y letra eñe):
*/

[IMAGEN]

/*
2. Se verifica que estén todas las columnas de la tabla TRANSPORTE en la tabla COMUNA, añadiendo las faltantes:
*/

SELECT comuna FROM TRANSPORTE MINUS SELECT nombre FROM COMUNA;

INSERT INTO COMUNA (region_id, nombre) VALUES ('RM', 'Conchalí');
INSERT INTO COMUNA (region_id, nombre) VALUES ('RM', 'Lo Espejo');
INSERT INTO COMUNA (region_id, nombre) VALUES ('RM', 'Renca');

/*
3. Se crea una columna id_direccion
*/

ALTER TABLE TRANSPORTE
ADD COLUMN id_direccion NUMBER;

/*
4. Se agregan las direcciones de la tabla TRANSPORTE en la tabla DIRECCION:
*/

INSERT INTO DIRECCION(direccion, id_comuna)
WITH d AS (SELECT direccion FROM TRANSPORTE MINUS SELECT direccion FROM DIRECCION)
SELECT DISTINCT(d.direccion), c."id" FROM d
INNER JOIN TRANSPORTE t
ON d.direccion = t.direccion
INNER JOIN COMUNA c
ON c.nombre = t.comuna;

/*
5. Se agregan los identificadores de dirección en cada fila de la tabla TRANSPORTE
*/

BEGIN
FOR i IN (SELECT "id", direccion FROM DIRECCION)
LOOP
UPDATE TRANSPORTE SET id_direccion = i."id"
WHERE direccion = i.direccion;
END LOOP;
END;

/*
6. Se eliminan las columnas que ahora son redundantes
*/

ALTER TABLE TRANSPORTE DROP COLUMN direccion;
ALTER TABLE TRANSPORTE DROP COLUMN comuna;