CREATE OR REPLACE ATTRIBUTE DIMENSION "ADMIN"."BOLETA_DETALLE_MODEL_BOLETA_AD"
 DIMENSION TYPE STANDARD
  CLASSIFICATION "CAPTION" VALUE 'BOLETA'
  CLASSIFICATION "DESCRIPTION" VALUE 'BOLETA'
  CLASSIFICATION "MODEL" VALUE 'BOLETA_DETALLE_MODEL'
 USING "BOLETA" AS "BOLETA"
 ATTRIBUTES (
  "BOLETA"."ESTADO" AS "ESTADO_ATTR"
   CLASSIFICATION "CAPTION" VALUE 'ESTADO_ATTR'
   CLASSIFICATION "DESCRIPTION" VALUE 'ESTADO_ATTR',
  "BOLETA"."FECHA_COMPRA" AS "FECHA_COMPRA_ATTR"
   CLASSIFICATION "CAPTION" VALUE 'FECHA_COMPRA_ATTR'
   CLASSIFICATION "DESCRIPTION" VALUE 'New Description1',
  "BOLETA"."MEDIO_PAGO" AS "MEDIO_PAGO_ATTR"
   CLASSIFICATION "CAPTION" VALUE 'MEDIO_PAGO_ATTR'
   CLASSIFICATION "DESCRIPTION" VALUE 'New Description1')
 LEVEL "ESTADO"
  KEY ("ESTADO_ATTR")
  MEMBER NAME to_char("ESTADO_ATTR")
  MEMBER CAPTION to_char("ESTADO_ATTR")
  MEMBER DESCRIPTION to_char("ESTADO_ATTR")
  ORDER BY MIN "ESTADO_ATTR" ASC NULLS FIRST
  DETERMINES ("ESTADO_ATTR")
 LEVEL "FECHA_COMPRA"
  KEY ("FECHA_COMPRA_ATTR")
  MEMBER NAME to_char("ESTADO_ATTR")
  MEMBER CAPTION to_char("FECHA_COMPRA_ATTR")
  MEMBER DESCRIPTION to_char("ESTADO_ATTR")
  ORDER BY MIN "FECHA_COMPRA_ATTR" ASC NULLS FIRST
  DETERMINES ("ESTADO_ATTR", "FECHA_COMPRA_ATTR")
 LEVEL "MEDIO_PAGO"
  KEY ("MEDIO_PAGO_ATTR")
  MEMBER NAME to_char("ESTADO_ATTR")
  MEMBER CAPTION to_char("MEDIO_PAGO_ATTR")
  MEMBER DESCRIPTION to_char("ESTADO_ATTR")
  ORDER BY MIN "MEDIO_PAGO_ATTR" ASC NULLS FIRST
  DETERMINES ("FECHA_COMPRA_ATTR", "MEDIO_PAGO_ATTR")
 ALL
  MEMBER NAME 'ALL'
  MEMBER CAPTION 'ALL'
  MEMBER DESCRIPTION 'ALL';
CREATE OR REPLACE ATTRIBUTE DIMENSION "ADMIN"."BOLETA_DETALLE_MODEL_ESTADO_AD"
 DIMENSION TYPE STANDARD
  CLASSIFICATION "CAPTION" VALUE 'ESTADO'
  CLASSIFICATION "DESCRIPTION" VALUE 'ESTADO'
  CLASSIFICATION "MODEL" VALUE 'BOLETA_DETALLE_MODEL'
 USING "BOLETA_DETALLE" AS "BOLETA_DETALLE"
 ATTRIBUTES (
  "BOLETA_DETALLE"."ESTADO" AS "ESTADO_ATTR"
   CLASSIFICATION "CAPTION" VALUE 'ESTADO_ATTR'
   CLASSIFICATION "DESCRIPTION" VALUE 'ESTADO_ATTR')
 LEVEL "ESTADO"
  KEY ("ESTADO_ATTR")
  MEMBER NAME to_char("ESTADO_ATTR")
  MEMBER CAPTION to_char("ESTADO_ATTR")
  MEMBER DESCRIPTION to_char("ESTADO_ATTR")
  ORDER BY MIN "ESTADO_ATTR" ASC NULLS FIRST
  DETERMINES ("ESTADO_ATTR")
 ALL
  MEMBER NAME 'ALL'
  MEMBER CAPTION 'ALL'
  MEMBER DESCRIPTION 'ALL';
CREATE OR REPLACE ATTRIBUTE DIMENSION "ADMIN"."BOLETA_DETALLE_MODEL_PRODUCTO_AD"
 DIMENSION TYPE STANDARD
  CLASSIFICATION "CAPTION" VALUE 'PRODUCTO'
  CLASSIFICATION "DESCRIPTION" VALUE 'PRODUCTO'
  CLASSIFICATION "MODEL" VALUE 'BOLETA_DETALLE_MODEL'
 USING "PRODUCTO" AS "PRODUCTO"
 ATTRIBUTES (
  "PRODUCTO"."ALTO" AS "ALTO_ATTR"
   CLASSIFICATION "CAPTION" VALUE 'TIPO_ATTR'
   CLASSIFICATION "DESCRIPTION" VALUE 'New Description1',
  "PRODUCTO"."TIPO" AS "TIPO_ATTR"
   CLASSIFICATION "CAPTION" VALUE 'TIPO_ATTR'
   CLASSIFICATION "DESCRIPTION" VALUE 'New Description1',
  "PRODUCTO"."id" AS "id_ATTR"
   CLASSIFICATION "CAPTION" VALUE 'id'
   CLASSIFICATION "DESCRIPTION" VALUE 'New Description1')
 LEVEL "TIPO"
  KEY ("TIPO_ATTR")
  MEMBER NAME to_char("ALTO_ATTR")
  MEMBER CAPTION to_char("TIPO_ATTR")
  MEMBER DESCRIPTION to_char("ALTO_ATTR")
  ORDER BY MIN "TIPO_ATTR" ASC NULLS FIRST
  DETERMINES ("ALTO_ATTR", "TIPO_ATTR")
 LEVEL "id"
  KEY ("id_ATTR")
  MEMBER NAME to_char("ALTO_ATTR")
  MEMBER CAPTION to_char("id_ATTR")
  MEMBER DESCRIPTION to_char("ALTO_ATTR")
  ORDER BY MIN "id_ATTR" ASC NULLS FIRST
  DETERMINES ("TIPO_ATTR", "id_ATTR")
 ALL
  MEMBER NAME 'ALL'
  MEMBER CAPTION 'ALL'
  MEMBER DESCRIPTION 'ALL';
CREATE OR REPLACE HIERARCHY "ADMIN"."BOLETA_DETALLE_MODEL_BOLETA_HIER"
  CLASSIFICATION "CAPTION" VALUE 'BOLETA'
  CLASSIFICATION "DESCRIPTION" VALUE 'BOLETA'
  CLASSIFICATION "MODEL" VALUE 'BOLETA_DETALLE_MODEL'
 USING "BOLETA_DETALLE_MODEL_BOLETA_AD"
  ("MEDIO_PAGO" CHILD OF "FECHA_COMPRA" CHILD OF "ESTADO");
CREATE OR REPLACE HIERARCHY "ADMIN"."BOLETA_DETALLE_MODEL_ESTADO_HIER"
  CLASSIFICATION "CAPTION" VALUE 'ESTADO'
  CLASSIFICATION "DESCRIPTION" VALUE 'ESTADO'
  CLASSIFICATION "MODEL" VALUE 'BOLETA_DETALLE_MODEL'
 USING "BOLETA_DETALLE_MODEL_ESTADO_AD"
  ("ESTADO");
CREATE OR REPLACE HIERARCHY "ADMIN"."BOLETA_DETALLE_MODEL_PRODUCTO_HIER"
  CLASSIFICATION "CAPTION" VALUE 'PRODUCTO'
  CLASSIFICATION "DESCRIPTION" VALUE 'PRODUCTO'
  CLASSIFICATION "MODEL" VALUE 'BOLETA_DETALLE_MODEL'
 USING "BOLETA_DETALLE_MODEL_PRODUCTO_AD"
  ("id" CHILD OF "TIPO");
CREATE OR REPLACE ANALYTIC VIEW "BOLETA_DETALLE_MODEL_AV"
 CLASSIFICATION "MODEL" VALUE 'BOLETA_DETALLE_MODEL'
 USING "BOLETA_DETALLE" AS "BOLETA_DETALLE"
 DIMENSION BY (
  "BOLETA_DETALLE_MODEL_ESTADO_AD" AS "BOLETA_DETALLE_MODEL_ESTADO_AD"
    KEY ("ESTADO") REFERENCES DISTINCT("ESTADO_ATTR")
    HIERARCHIES ("BOLETA_DETALLE_MODEL_ESTADO_HIER" AS "BOLETA_DETALLE_MODEL_ESTADO_HIER" DEFAULT),
  "BOLETA_DETALLE_MODEL_PRODUCTO_AD" AS "BOLETA_DETALLE_MODEL_PRODUCTO_AD"
   CLASSIFICATION "CAPTION" VALUE 'PRODUCTO'
   CLASSIFICATION "DESCRIPTION" VALUE 'PRODUCTO'
    KEY ("ID_PRODUCTO") REFERENCES ("id_ATTR")
    HIERARCHIES ("BOLETA_DETALLE_MODEL_PRODUCTO_HIER" AS "BOLETA_DETALLE_MODEL_PRODUCTO_HIER" DEFAULT))
 MEASURES (
  "CANTIDAD_VENDIDA_SUM" FACT "CANTIDAD_VENDIDA" AGGREGATE BY SUM
    CLASSIFICATION "AVX_DATA_TYPE" VALUE 'NUMBER'
    CLASSIFICATION "CAPTION" VALUE 'CANTIDAD_VENDIDA_SUM'
    CLASSIFICATION "DESCRIPTION" VALUE 'Total de la cantidad vendida'
,  "MONTO_SUM" FACT "MONTO" AGGREGATE BY SUM
    CLASSIFICATION "AVX_DATA_TYPE" VALUE 'NUMBER'
    CLASSIFICATION "CAPTION" VALUE 'MONTO_SUM'
    CLASSIFICATION "DESCRIPTION" VALUE 'Monto total de venta'
,  "CANTIDAD_VENDIDA_AVG" FACT "CANTIDAD_VENDIDA" AGGREGATE BY AVG
    CLASSIFICATION "AVX_DATA_TYPE" VALUE ''
    CLASSIFICATION "CAPTION" VALUE 'CANTIDAD_VENDIDA_AVG'
    CLASSIFICATION "DESCRIPTION" VALUE 'Promedio de la cantidad vendida'
,  "CANTIDAD_VENDIDA_MIN" FACT "CANTIDAD_VENDIDA" AGGREGATE BY MIN
    CLASSIFICATION "AVX_DATA_TYPE" VALUE ''
    CLASSIFICATION "CAPTION" VALUE 'CANTIDAD_VENDIDA_MIN'
    CLASSIFICATION "DESCRIPTION" VALUE 'Cantidad vendida mínima'
,  "CANTIDAD_VENDIDA_MAX" FACT "CANTIDAD_VENDIDA" AGGREGATE BY MAX
    CLASSIFICATION "AVX_DATA_TYPE" VALUE ''
    CLASSIFICATION "CAPTION" VALUE 'CANTIDAD_VENDIDA_MAX'
    CLASSIFICATION "DESCRIPTION" VALUE 'Cantidad vendida máxima'
,  "MONTO_AVG" FACT "MONTO" AGGREGATE BY AVG
    CLASSIFICATION "AVX_DATA_TYPE" VALUE ''
    CLASSIFICATION "CAPTION" VALUE 'MONTO_AVG'
    CLASSIFICATION "DESCRIPTION" VALUE 'Monto promedio de venta'
,  "MONTO_MIN" FACT "MONTO" AGGREGATE BY MIN
    CLASSIFICATION "AVX_DATA_TYPE" VALUE ''
    CLASSIFICATION "CAPTION" VALUE 'MONTO_MIN'
    CLASSIFICATION "DESCRIPTION" VALUE 'Monto mínimo de venta'
,  "MONTO_MAX" FACT "MONTO" AGGREGATE BY MAX
    CLASSIFICATION "AVX_DATA_TYPE" VALUE ''
    CLASSIFICATION "CAPTION" VALUE 'MONTO_MAX'
    CLASSIFICATION "DESCRIPTION" VALUE 'Monto máximo de venta'
)
 DEFAULT MEASURE "CANTIDAD_VENDIDA_SUM"
 DEFAULT AGGREGATE BY SUM
FACT COLUMNS ("CANTIDAD_VENDIDA","ESTADO","ID_BOLETA","ID_PRODUCTO","MONTO");
